### ISSUE TITLE
希望增加模糊查询功能和清空功能

### ISSUE THREAD

**Issue by zhxuyang11** [cmdparkour/layuiCascader#4]

**Comment by cmdparkour** [comment]
基于异步的特点，暂时只有单项的搜索功能，如果要做真正的查询的话，得拉取所有的数据进入，目前暂不支持此功能，后续会增加另一种思路的搜索功能，但由于目前没有构思好，只能先放置了

**Comment by cmdparkour** [comment]
已增加异步查询功能，以及清空功能
